### ISSUE TITLE
Do not use tabs as indentation

### ISSUE THREAD

**Issue by phoe** [j3pic/simple-actors#3]
https://github.com/j3pic/simple-actors/blob/1a0dd0528db6ccf30088f9bbbd575837735d2d8a/better-handler-case.lisp#L11

**Comment by j3pic** [comment]
I can't control how Emacs indents Lisp.

**Comment by phoe** [comment]
I think you can: https://www.emacswiki.org/emacs/NoTabs

```lisp
(setq-default indent-tabs-mode nil)
```
